/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001d36",
        "outline": "#916f6f",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#181c21",
        "tertiary-fixed": "#d1e4ff",
        "surface-tint": "#bf0031",
        "on-primary-fixed": "#40000a",
        "secondary-container": "#dde0e6",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#c3c6cd",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed-variant": "#43474d",
        "primary": "#bd0030",
        "primary-container": "#e61e43",
        "surface-variant": "#e0e3e5",
        "tertiary": "#0061a3",
        "surface-container-lowest": "#ffffff",
        "secondary": "#5b5f64",
        "surface": "#f7f9fb",
        "tertiary-container": "#007acb",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-primary": "#ffffff",
        "outline-variant": "#e6bdbd",
        "surface-bright": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#ffb3b4",
        "on-primary-fixed-variant": "#920023",
        "tertiary-fixed-dim": "#9ecaff",
        "on-tertiary-fixed-variant": "#00497d",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#e0e2e9",
        "primary-fixed": "#ffdad9",
        "on-tertiary-container": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#5f6369",
        "error": "#ba1a1a",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb3b4",
        "on-surface-variant": "#5c3f40",
        "surface-container-highest": "#e0e3e5"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      spacing: {
        "sidebar-width": "260px",
        "container-padding": "24px",
        "card-gap": "16px",
        "gutter": "20px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
